# Generated by Django 5.1.1 on 2025-05-13 02:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacias',
            fields=[
                ('id_farmacia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=5)),
                ('municipio', models.CharField(max_length=255)),
                ('nome_farmacia', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=255)),
            ],
        ),
    ]
